apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: product
type: Opaque
stringData:
  DB_HOST: "your-cloud-sql-host"
  DB_NAME: "productdb"
  DB_USERNAME: "your-db-username"
  DB_PASSWORD: "your-db-password"